global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'task-service'
    static_configs:
      - targets: ['task-service:3002']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'search-service'
    static_configs:
      - targets: ['search-service:3003']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'content-service'
    static_configs:
      - targets: ['content-service:3004']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'monitoring-service'
    static_configs:
      - targets: ['monitoring-service:3005']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: '/_prometheus/metrics'
    scrape_interval: 30s
