apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-engine
  namespace: skills-platform
  labels:
    app: matching-engine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: matching-engine
  template:
    metadata:
      labels:
        app: matching-engine
    spec:
      containers:
      - name: matching-engine
        image: matching-engine:latest
        ports:
        - containerPort: 3006
        envFrom:
        - configMapRef:
            name: skills-platform-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3006
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3006
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: matching-engine
  namespace: skills-platform
spec:
  selector:
    app: matching-engine
  ports:
  - port: 3006
    targetPort: 3006
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: matching-engine-hpa
  namespace: skills-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: matching-engine
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
